// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNmJzfgEWJhafxdMnl8wNq0LOFRpEi68I',
    appId: '1:199963727378:web:578cd92c75749059762acb',
    messagingSenderId: '199963727378',
    projectId: 'shop-application-171d5',
    authDomain: 'shop-application-171d5.firebaseapp.com',
    storageBucket: 'shop-application-171d5.appspot.com',
    measurementId: 'G-YCQMWSENK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcDTTUDHgqAQqs1eZLMZMy4tLitamCVnU',
    appId: '1:199963727378:android:c04cadb604328f8b762acb',
    messagingSenderId: '199963727378',
    projectId: 'shop-application-171d5',
    storageBucket: 'shop-application-171d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFLq72GcfLJ4bLlbYd9Saajqjp6rUZOOg',
    appId: '1:199963727378:ios:aed9c9180915c76a762acb',
    messagingSenderId: '199963727378',
    projectId: 'shop-application-171d5',
    storageBucket: 'shop-application-171d5.appspot.com',
    iosClientId: '199963727378-9n6h121rodfrt6ani82kqk93qa672rn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFLq72GcfLJ4bLlbYd9Saajqjp6rUZOOg',
    appId: '1:199963727378:ios:aed9c9180915c76a762acb',
    messagingSenderId: '199963727378',
    projectId: 'shop-application-171d5',
    storageBucket: 'shop-application-171d5.appspot.com',
    iosClientId: '199963727378-9n6h121rodfrt6ani82kqk93qa672rn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApplication',
  );
}
